### ISSUE TITLE
Gradle dependency resolve error

### ISSUE THREAD

**Issue by aleksandr1592** [wunderlist/android-sliding-layer-lib#81] opened 2015-07-19 12:37 UTC
Hello.My gradle can't resolve dependency compile 'com.wunderlist:sliding-layer:1.2.5' but  'com.wunderlist:sliding-layer:1.1.1' resolving fine.Am I doing something wrong?
My build.gradle in app root
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }

    defaultConfig {
        applicationId "com.aleksandrz.testapp"
        minSdkVersion 9
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.facebook.fresco:fresco:0.5.2'
    compile 'com.android.support:cardview-v7:22.1.1'
    compile 'com.pixplicity.easyprefs:library:1.4'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.github.rey5137:material:1.1.1'
    compile 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
    compile 'com.navercorp.pulltorefresh:library:3.2.0@aar'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.squareup.picasso:picasso:2.3.3'
    compile 'org.jsoup:jsoup:1.8.1'
    compile (
            [group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.4.1'],
            [group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.4.1'],
            [group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.4.1']
    )
    compile 'com.github.florent37:materialimageloading:1.0.0'
    compile 'com.android.support:design:22.2.0'
    compile "com.wefika:flowlayout:0.4.0"
    compile 'com.wunderlist:sliding-layer:1.1.
}
```
My build.gradle in project root
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

**Comment by JlUgia** [comment] 2015-07-19 21:26
Hey @aleksandr1592, you are all good. Version 1.2.5 has not been yet uploaded to Maven or Jcenter. @CesarValiente is finishing up on that. Maybe good time to get to automate that.

**Comment by crysan** [comment] 2015-07-31 03:10
compile 'com.wunderlist:sliding-layer:1.2.5'
NOT WORK !!!

**Comment by JlUgia** [comment] 2015-07-31 08:29
Hi @crysan . Please read my comment above.

**Comment by crysan** [comment] 2015-08-01 00:01
Once your comment has been 12 days.  I thought that the problem is solved already.  And I do not understand why so long, if you already have a ready library.

**Comment by aleksandr1592** [comment] 2015-08-01 04:29
@crysan If you really want latest changes, you  can use jitpack.io like i did.
BTW They don't have to update library.They don't even have to put it github.If you dont like this library you can always make your own.

**Comment by JlUgia** [comment] 2015-08-01 13:16
Thanks to both of you for your comments. @aleksandr1592, @crysan is right in the sense that if we open source a library the goal is to make it available as soon as possible, but thanks for looking for alternative ways to use it. 
@crysan i's definitely our goal to have this out asap, unfortunately open source projects are not yet included on the daily work schedule of some of us. Hopefully this changes soon.

Nevertheless and that's part of the beauty of open source, there are tools in Gradle to make the publishing process automatic. How do you feel about creating a PR with that? We'll do it anyway sooner or later.

Don't worry, this version will be uploaded to Jcenter in the next days anyway. In the meantime, consider using it as a git submodule inside of your projects.

Thanks again.

**Comment by crysan** [comment] 2015-08-03 00:13
Thank you and waiting...

**Comment by CesarValiente** [comment] 2015-08-12 08:20
Hi guys, the library is already published on MavenCentral, and along the day it will be in JCenter.
Thanks for your patience.

@aleksandr1592 thanks for your comment mate :-)

PS: I will close the issue as soon as I see the library on JCenter.

**Comment by CesarValiente** [comment] 2015-08-12 12:14
The lib is already in Jcenter too. Enjoy :-)

**Closed by CesarValiente** 2015-08-12 12:14 UTC
